spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://1.15.53.152:3306/lowtmall_ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: Llt619tlL.mysql
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: lowt-member
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8079